# General seekr application config
[general]

# search placeholder text
search_placeholder = %PLACEHOLDER%

# icon theme
theme = Adwaita

# terminal used to run shell based programs
terminal = kitty

# terminal launch args
args = -e

# Configuration for the layer-shell protocol
# Use the <ESC> key to close the layer
[gtk-layer-shell]
# set gtk-layer-shell as active
# Will try to fallback to default window if protocol non available
active = false

# set the top offset of the window
# A negative value will center verticaly it on the screen
top = 50

# set the left offset of the window
# A negative value will center it horizontaly on the screen
left = -1

# macros configuration
# .... <name> = <cmd>
# .... <name>|<display_name> = <cmd>
# .... display_name is the text that substitute the macro base name
# .... Available variables
# .... - ENTRY      : the user query
# .... - CONFIG_DIR : directory where the config is set up
# .... '@<name> ' to call a macro
[macros]
ddg|DuckDuckGo = xdg-open https://duckduckgo.com/?q={ENTRY}
google = xdg-open https://www.google.com/search?q={ENTRY}
