# General seekr application config
[general]

# search placeholder text
# search_placeholder = %PLACEHOLDER%

# icon theme
theme = Adwaita

# terminal used to run shell based programs
terminal = kitty

# terminal launch args
args = -e

# macros configuration
# .... <name> = <cmd>
# .... <name>|<display_name> = <cmd>
# .... display_name is the text that substitute the macro base name
# .... Available variables
# .... - ENTRY      : the user query
# .... - CONFIG_DIR : directory where the config is set up
# .... '@<name> ' to call a macro
[macros]
ddg|DuckDuckGo = xdg-open https://duckduckgo.com/?q={ENTRY}
google = xdg-open https://www.google.com/search?q={ENTRY}
