# General seekr application config
[general]

# search placeholder text
# search_placeholder = %PLACEHOLDER%

# icon theme
theme = Adwaita

# terminal used to run shell based programs
terminal = kitty

# terminal launch args
args = -e

# macros configuration
# .... <name> = <cmd>
# .... Available variables
# .... - ENTRY : the user query
# .... '@<name> ' to call a macro
[macros]
google = xdg-open https://www.google.com/search?q={ENTRY}
